name: Pull Request Validation

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  job1:
    name: Get working branch
    runs-on: [ubuntu-latest]
    outputs:
      extract_branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Branch used
        id: extract_branch
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
            echo "::set-output name=branch::$(echo ${GITHUB_REF##*/})"
          elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "::set-output name=branch::$(echo $GITHUB_BASE_REF)"
          else
            echo "::set-output name=branch::INVALID_EVENT_BRANCH_UNKNOWN"
          fi

  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Echo values
        shell: bash
        run: |
          echo "Pull request's branch is: ${BRANCH}"
          echo "Pull request's base branch is: ${BASE_BRANCH}"
          echo "ref ${{github.ref}}"
          echo "title ${{ github.event.pull_request.title}}"
          echo "event ${{github.event_name}}"
          echo "ref ${GITHUB_REF##*/}"
          echo "pr ref ${{ github.event.pull_request.base.ref }}"
          echo "pr ref ${{ github.event.pull_request.base.ref }}"
          echo "pr ref_name ${{ github.event.pull_request.base.ref_name }}"
          echo "$GITHUB_BASE_REF"
          echo "${GITHUB_REF##*/}"
        env:
          BASE_BRANCH: ${{ github.base_ref }}
          BRANCH: ${{ github.ref_name }}
      - name: Validating branch name
        shell: bash
        run: | 
          echo Testing branch name: ${GITHUB_REF##*/}

          project1="SWISCO-"
          project2="SWISCA-"
          ticket_number="([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][0-9])"
          if [[ ! "${GITHUB_REF##*/}" =~ $project1$ticket_number && ! "${GITHUB_REF##*/}" =~ $project2$ticket_number ]]; then
            echo "Branch name should contain JIRA ticket, like..."
            echo " SWISCO-1234-short-description"
            echo " feature/SWISCO-1234-short-description"
            echo " release/SWISCA-1234-short-description"
            exit 1
          fi
      - name: Validating title
        shell: bash
        run: | 
          echo Testing title: ${{ github.event.pull_request.title }}
      - name: force-fail
        shell: bash
        run: | 
          echo Force fail
          if [[ 1 == 1 ]]; then
            echo "Force fail"
            exit 1
          fi
