on:
  push:
  pull_request:

name: Pull Request Validation

jobs:
  validate:

    env:
      BASE_BRANCH: ${{ github.base_ref }}
      BRANCH: ${{ github.ref_name }}
      project1_name: "SWISCO-"
      project2_name: "SWISCA-"
      ticket_number_regex: "([1-9]|[1-9][0-9]|[1-9][0-9][0-9]|[1-9][0-9][0-9][0-9])"
      pr_title: ${{ github.event.pull_request.title }}
      event_type: ${{github.event_name}}

    runs-on: ubuntu-latest

    steps:

      - name: Echo values
        shell: bash
        run: |
          echo "Pull request's branch is: ${BRANCH}"
          echo "Pull request's base branch is: ${BASE_BRANCH}"
          echo "ref ${{github.ref}}"
          echo "title ${{ github.event.pull_request.title}}"
          echo "event ${{github.event_name}}"
          echo "ref ${GITHUB_REF##*/}"
          echo "pr ref ${{ github.event.pull_request.base.ref }}"
          echo "pr ref ${{ github.event.pull_request.base.ref }}"
          echo "pr ref_name ${{ github.event.pull_request.base.ref_name }}"
          echo "$GITHUB_BASE_REF"
          echo "${GITHUB_REF##*/}"
          echo "GITHUB_REF_NAME ${GITHUB_REF_NAME}"

      - name: Validating branch name
        shell: bash
        if: ${{ github.event_name == 'push' }}
        run: | 
          echo "Testing branch name: ${BRANCH^^}"
          if [[ ! "${BRANCH^^}" =~ $project1_name$ticket_number_regex && ! "${BRANCH^^}" =~ $project2_name$ticket_number_regex ]]; then
            echo "The branch name must contain the JIRA ticket, like..."
            echo " SWISCO-1234-short-description"
            echo " feature/SWISCO-1234-short-description"
            echo " release/SWISCA-1234-short-description"
            exit 1
          else
            echo "Branch name is good."
          fi

      - name: Validating title
        shell: bash
        if: ${{ github.event_name == 'pull_request' }}
        run: | 
          echo "Testing title: ${pr_title^^}"
          if [[ ! "${pr_title^^}" =~ $project1_name$ticket_number_regex && ! "${pr_title^^}" =~ $project2_name$ticket_number_regex ]]; then
            echo "The Pull Request title must contain the JIRA ticket, like..."
            echo "SWISCO-1234 Title description of the change"
            echo "Feature/SWISCO-1234 Title description of the change"
            exit 1
          else
            echo "Title is good."
          fi

